---
apiVersion: v1
kind: Pod
metadata:
  name: export-snapshot
  labels:
    app: export-snapshot
spec:
  containers:
  - image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
    command: ["/bin/bash", "-c"]
    args:
      - sleep infinity
    name: sleep
    securityContext:
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      runAsNonRoot: true
      capabilities:
        drop:
        - ALL
    volumeMounts:
      - mountPath: /snapshot
        name: snapshot
  terminationGracePeriodSeconds: 2
  volumes:
  - name: snapshot
    persistentVolumeClaim:
      claimName: etherpad-snapshot