apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  pipelines:
  - name: all-to-default
    inputRefs:
    - CHANGE_ME
    - CHANGE_ME
    - CHANGE_ME
    outputRefs:
    - CHANGE_ME
