apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: CHANGE_ME
  name: CHANGE_ME
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - contents:
            compression: ""
            source: data:;base64,CHANGE_ME
          mode: 420
          overwrite: true
          path: /etc/chrony.conf
