apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: k8s-deploy-prod
bases:
  - ../../base
images:
  - name: registry.ocp4.example.com:8443/redhattraining/versioned-hello
    newTag: v1.1
