apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
spec:
  servingCerts:
    namedCertificates:
    - names:
      - <MASTER-API>
      servingCertificate:
        name: <SECRET-NAME>
