apiVersion: v1
kind: Secret
metadata:
  name: htpasswd-secret
  namespace: openshift-config
type: Opaque
stringData:
  htpasswd: |
    abbyquincy:$2y$05$wlnMNEC7g6ue2ZeMb5y1CeKD5OeyjuaCKL46HZ2ad1ouvRFJawFSu
    fricisritcher:$2y$05$IJQONxRmA9KIevo0PbCZgeSB.QGZIfyuPLVGHFncEZzwzMbjVvn4W
