apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - ldap:
      attributes:
        email:
          - mail
        id:
          - dn
        name:
          - cn
        preferredUsername:
          - uid
      bindDN: uid=admin,cn=users,cn=accounts,dc=ocp4,dc=example,dc=com
      bindPassword:
        name: ldap-secret
      ca:
        name: ca-config-map
      insecure: false
      url: >-
        ldap://idm.ocp4.example.com/cn=users,cn=accounts,dc=ocp4,dc=example,dc=com?uid
    mappingMethod: claim
    name: Red Hat Identity Management
    type: LDAP
  - htpasswd:
      fileData:
        name: htpasswd-secret
    mappingMethod: claim
    name: htpasswd_provider
    type: HTPasswd
  - openID:
      claims:
        email:
          - email
        name:
          - name
        preferredUsername:
          - preferred_username
        groups:
          - groups
      clientID: ocp_rhsso
      clientSecret:
        name: rhsso-oidc-client-secret
      extraScopes: []
      issuer: >-
        https://sso.ocp4.example.com:8080/auth/realms/external_providers
    mappingMethod: claim
    name: RHSSO_OIDC
    type: OpenID
