apiVersion: v1
kind: Namespace
metadata:
  name: k8s-deploy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hello-dev
  namespace: k8s-deploy
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: developer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
