---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: logging-deploy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger
  namespace: logging-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
      - image: registry.ocp4.example.com:8443/redhattraining/access-logger:v0.1
        name: logger
...
